---
mmdebstrap:
  architectures:
    - arm64
  mode: auto
  keyrings:
    - /usr/share/keyrings/debian-archive-keyring.gpg
  suite: bookworm
  variant: standard
  hostname: localhost
  components:
    - main
    - contrib
    - non-free-firmware
  packages:
    #- build-essential
    - gpg
    - init
    - iproute2
    - less
    - libdrm-dev
    - libpam-systemd
    - locales
    - neofetch
    - sudo
    - linux-libc-dev
    - parted
    - e2fsprogs
    - openssh-server
    - tmux
    - vim
    - nano
    - telnet
    - picocom
    - wget
    - curl
    - openssl
    - libssl-dev
    - libreswan
    - python3
    - python3-distutils
    - python3-pyinotify
    - libpython3-dev
    - network-manager
    - firewalld
    - rsync
    - netcat-openbsd
    - socat
    - tcpdump
    - libcap-ng-utils
    - strace
    - net-tools
    - lm-sensors
    - gnupg2
    - binutils-dev
    - snmp
    - libsnmp-dev
    - dos2unix
    - logrotate
    - rsyslog
    - nethogs
    - lsof
    - sysstat
    - iotop
    - htop
    - make
    - udev
    - file
    - ethtool
    - apt
    - apt-utils
    - gcc-11-base
    - zip
    - libxml2-dev
    - liblzma-dev
    - dpkg
    - can-utils
    - fdisk
    - dbus
    - sqlite3
    - rsync
    - autoconf
    - automake
    - dh-autoreconf
    - libpcap-dev
    - bc
    - bridge-utils
    - libtool
    - libncurses5-dev
    - bison
    - libelf-dev
    - libc-bin
    - dialog
    - rng-tools-debian
    - mysql-common
    - systemd
    - systemd-sysv
    - autotools-dev
    - openssh-client
    - vlan
    - ifenslave
    - mdadm
    - isc-dhcp-client
    - i2c-tools
    - memtool
    - gettext
    - patch
    - systemd-container
    - rdate
    - initramfs-tools
    - mtd-utils
    - dosfstools
    - pciutils
    - iputils-ping
    - hdparm
    - psmisc
    - software-properties-common
    - libreadline8
    - bzip2
    - lz4
    - bsdmainutils
    - patchelf
    - cpuinfo
    - libssl-dev
    - ca-certificates
    - libnl-genl-3-dev
    - libreadline-dev
    - libudev-dev
    - libpam0g-dev
    - lsb-release
    - iptables
    - usbutils
    - ppp
    - unzip
    - usb.ids
    - util-linux
    - lshw,keyutils
    - libsystemd-dev
    - libxcursor-dev
    - snmpd
    - minicom
    - exfat-fuse
    - udhcpc
    - udhcpd
    - mmc-utils
    - wpasupplicant
    - wireless-tools
    - iw
    - wireless-regdb
    - fbset
    - alsa-utils
    - zstd
    - libhugetlbfs0
    - kexec-tools
    - flex
    - rt-tests
    - linuxptp
    - mosquitto
    - bluez
    - v4l-utils
    - dmidecode
    - lighttpd
    #- chrony
    #- systemd-timesyncd
    #- ntpsec
    #- ntpsec-ntpdate    
  mirrors:
    - http://deb.debian.org/debian
  #setup-hooks:
      # Setup TI Debian Package Repository
    #- 'mkdir -p $1/etc/apt/sources.list.d/'
    #- 'wget https://raw.githubusercontent.com/TexasInstruments/ti-debpkgs/main/ti-debpkgs.sources -P $1/etc/apt/sources.list.d/'
      # Setup Apt repository preferences
    #- 'mkdir -p $1/etc/apt/preferences.d/'
    #- 'printf "Package: *\nPin: origin TexasInstruments.github.io\nPin-Priority: 1001" >> $1/etc/apt/preferences.d/ti-debpkgs'
      # Setup Kernel post-install scripts
    #- 'mkdir -p $1/etc/kernel/postinst.d/'
    #- 'echo "PWD = $PWD"'
    #- 'upload target/kernel/postinst.d/cp-kernel-and-overlays /etc/kernel/postinst.d/cp-kernel-and-overlays'
    #- 'chmod a+x $1/etc/kernel/postinst.d/cp-kernel-and-overlays'
  essential-hooks:
    # FIXME: Find a better workaround instead of sleep
    - 'sleep 10' # workaround for /proc resource busy unable to umount issue
  customize-hooks:
      # Remove passwd for root user
    - 'chroot "$1" passwd --delete root'
      # Fix apt install mandb permission issue
    - 'chroot "$1" chown -R man: /var/cache/man/'
    - 'chroot "$1" chmod -R 755 /var/cache/man/'
      # update packages to avoid mandatory update after first boot
    - 'chroot "$1" apt-get update'
    - 'chroot "$1" apt-get -y install ntpsec ntpsec-ntpdate'
      # Setup .bashrc for clean command-line experience
    - 'chroot "$1" cp /etc/skel/.bashrc ~/.bashrc'
      # Enable ssh to root user without password
    - 'chroot "$1" echo "PermitRootLogin yes" >> $1/etc/ssh/sshd_config'
    - 'chroot "$1" echo "PermitEmptyPasswords yes" >> $1/etc/ssh/sshd_config'
      # Resize Rootfs Service
    #- 'chroot "$1" mkdir -p /usr/bin'
    #- 'upload target/resize_rootfs/resize_rootfs.sh /usr/bin/resize_rootfs.sh'
    #- 'chroot "$1" chmod a+x /usr/bin/resize_rootfs.sh'
    #- 'chroot "$1" mkdir -p /etc/systemd/system/'
    #- 'upload target/resize_rootfs/resize_rootfs.service /etc/systemd/system/resize_rootfs.service'
    #- '$BDEBSTRAP_HOOKS/enable-units "$1" resize_rootfs'

